#!/bin/bash
# Generate hosts/{hostname}.yaml from system inventory

set -e

show_help() {
    cat << 'EOF'
host-config.sh - Generate hosts/{hostname}.yaml from system inventory

Usage:
  host-config.sh [options]
  make host-config [FORCE=1]

Options:
  --help, -h    Show this help message
  --force, -f   Overwrite existing config file

Environment Variables:
  FORCE=1       Same as --force (for make compatibility)

Description:
  Generates a hosts/*.yaml configuration file by gathering system information:
  - Network bridges (vmbr*) with IPs and ports
  - ZFS pools and devices
  - SSH access configuration
  - Hardware info (CPU cores, memory)

  Run this on each physical host to bootstrap its configuration.

Examples:
  ./scripts/host-config.sh              # Generate config (fails if exists)
  ./scripts/host-config.sh --force      # Overwrite existing config
  make host-config FORCE=1              # Via Makefile
EOF
    exit 0
}

# Parse arguments
FORCE="${FORCE:-0}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            show_help
            ;;
        --force|-f)
            FORCE=1
            shift
            ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Use --help for usage information." >&2
            exit 1
            ;;
    esac
done

HOSTNAME=$(hostname -s)
OUTPUT_FILE="hosts/${HOSTNAME}.yaml"

# Check if file exists
if [ -f "$OUTPUT_FILE" ] && [ "$FORCE" != "1" ]; then
    echo "ERROR: $OUTPUT_FILE already exists. Use FORCE=1 to overwrite." >&2
    exit 1
fi

# Warn if not root
if [ "$(id -u)" != "0" ]; then
    echo "WARNING: Not running as root. Some information may be incomplete." >&2
fi

# Extract domain from FQDN or resolv.conf
DOMAIN=""
FQDN=$(hostname -f 2>/dev/null || echo "")
if [ -n "$FQDN" ] && [ "$FQDN" != "$HOSTNAME" ]; then
    DOMAIN="${FQDN#*.}"
fi
if [ -z "$DOMAIN" ] && [ -f /etc/resolv.conf ]; then
    DOMAIN=$(grep -m1 '^search\|^domain' /etc/resolv.conf 2>/dev/null | awk '{print $2}' || true)
fi

# Get SSH configuration
SSH_PORT=$(grep -E "^Port\s+" /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo "22")
SSH_PERMIT_ROOT=$(grep -E "^PermitRootLogin\s+" /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo "prohibit-password")
SSH_PASSWORD_AUTH=$(grep -E "^PasswordAuthentication\s+" /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo "no")

# Get hardware info
CPU_CORES=$(nproc 2>/dev/null || echo "unknown")
MEMORY_GB=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo "unknown")

# Start YAML output
cat <<EOF
# Auto-generated by: make host-config
# Host: $HOSTNAME
# Date: $(date -Iseconds)

host: $HOSTNAME
EOF

# Add domain if detected
if [ -n "$DOMAIN" ]; then
    echo "domain: $DOMAIN"
else
    echo "# domain: example.com  # Set manually if needed"
fi

# Get bridges and their config
BRIDGES=$(ip -j link show type bridge 2>/dev/null | python3 -c "import sys,json; [print(x['ifname']) for x in json.load(sys.stdin)]" 2>/dev/null || true)

if [ -z "$BRIDGES" ]; then
    echo ""
    echo "network:"
    echo "  interfaces: {}"
else
    echo ""
    echo "network:"
    echo "  interfaces:"
fi

for bridge in $BRIDGES; do
    # Get IP address for this bridge
    ip_addr=$(ip -j addr show dev "$bridge" 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for iface in data:
    for addr in iface.get('addr_info', []):
        if addr.get('family') == 'inet':
            print(f\"{addr['local']}/{addr['prefixlen']}\")
            break
" 2>/dev/null || true)

    # Get bridge ports
    ports=$(bridge link show 2>/dev/null | grep "master $bridge" | awk '{print $2}' | sed 's/:$//' | tr '\n' ',' | sed 's/,$//' || true)

    # Get gateway if this bridge has the default route
    gateway=$(ip -j route show default 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for route in data:
    if route.get('dev') == '$bridge':
        print(route.get('gateway', ''))
        break
" 2>/dev/null || true)

    echo "    $bridge:"
    echo "      type: bridge"
    if [ -n "$ports" ]; then
        echo "      ports: [${ports}]"
    else
        echo "      ports: []"
    fi
    if [ -n "$ip_addr" ]; then
        echo "      address: $ip_addr"
    fi
    if [ -n "$gateway" ]; then
        echo "      gateway: $gateway"
    fi
done

# ZFS pools
if command -v zpool >/dev/null 2>&1; then
    pools=$(zpool list -H -o name 2>/dev/null || true)
    if [ -n "$pools" ]; then
        echo ""
        echo "storage:"
        echo "  zfs_pools:"
        for pool in $pools; do
            echo "    - name: $pool"
            # Get devices for this pool (simplified - just top-level vdevs)
            devices=$(zpool list -vH "$pool" 2>/dev/null | awk 'NR>1 && $1 !~ /^(mirror|raidz|spare|log|cache|special)/ {print $1}' | tr '\n' ',' | sed 's/,$//' || true)
            if [ -n "$devices" ]; then
                echo "      devices: [${devices}]"
            else
                echo "      devices: []"
            fi
        done
    fi
fi

# Hardware section
echo ""
echo "hardware:"
echo "  cpu_cores: $CPU_CORES"
echo "  memory_gb: $MEMORY_GB"

# Access section
echo ""
echo "access:"
echo "  host_user: root"
echo "  ssh_port: $SSH_PORT"
echo "  authorized_keys: []  # TODO: add user@host references from secrets.ssh_keys"

# SSH settings
echo ""
echo "ssh:"
echo "  permit_root_login: $SSH_PERMIT_ROOT"
echo "  password_authentication: $SSH_PASSWORD_AUTH"

# Timezone
echo ""
echo "# Timezone inherited from site.yaml (uncomment to override)"
echo "# timezone: $(cat /etc/timezone 2>/dev/null || echo 'UTC')"
